### PR TITLE
TraceMode

### PR DESCRIPTION
**Pull request by NickKlock**
Tracing a player instead of fixed coordinates.

### CODE REVIEW

**Comment by tuthienloc92bk** [comment]
It will target the same mob which traced-player target, right?

**Comment by SDClowen** [comment]
> 

Which message you are talking for? Please replly to related message :)

**Comment by NickKlock** [comment]
> It will target the same mob which traced-player target, right?

you can choose to do that or just normaly select a mob around the radius of the traced player.

**Comment by SDClowen** [comment]
@NickKlock Will you continue develop to this pr? Please check my comments on your code files.

**Pull request closed without merging**
