### PR TITLE
trsro 14.02.2024 update compatibility changes

### PR DESCRIPTION
**Pull request by simsekahmett**

### CODE REVIEW

**Comment by Nero2200** [comment]
Trsro v 1.040 bot no't work

**Comment by Nero2200** [comment]
Usddddddddddntitled
Untitlddddddddddddddded

**Comment by Nero2200** [comment]
bot can't open sro_client.exe  in Trsro

**Comment by simsekahmett** [comment]
you can login after the PR completed.

**Comment by Nero2200** [comment]
The same problem in Trsro v 1.040   v rsbot 2.9.5  + 2.9.6  
UnSSSSSSSSSStitled
Can we fix the problem?

**Comment by Nero2200** [comment]
This problem does not exist in old versions. Now old versions do not work

**Pull request merged**
